config/routes.rb
Rails.application.routes.draw do
  scope ":locale", locale: /#{I18n.available_locales.join("|")}/ do
    root 'pages#home'
    get 'accommodation' => 'pages#accommodation'
    get 'afterparty' => 'pages#afterparty'
    post 'afterparty' => 'pages#create_afterparty'
    get 'afterparty/index' => 'pages#afterparty_index'
    get 'registry' => 'pages#registry'
    get 'rsvp' => 'pages#rsvp'
    post 'rsvp' => 'pages#create'
    get 'rsvp/index' => 'pages#rsvp_index'
    get 'video' => 'pages#video'
  end
  match '*path', to: redirect("/#{I18n.locale}/%{path}"), :via => [:get, :post]
  match '', to: redirect("/#{I18n.locale}"), :via => [:get, :post]
end

app/models/afterparty.rb
class Afterparty < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

  def accommodation

  end

  def afterparty
    @afterparty = Afterparty.new
  end

  def create_afterparty
    @afterparty = Afterparty.new(afterparty_params)
    if @afterparty.save
      redirect_to action: 'home'
    else
      render 'afterparty'
    end
  end

  def afterparty_index
    @afterparties = Afterparty.all
    @afterparty_count = Afterparty.all.size
  end

  def rsvp
    @rsvp = Rsvp.new
  end

  def create
    @rsvp = Rsvp.new(rsvp_params)
    if @rsvp.save
      redirect_to action: 'home'
    else
      render 'rsvp'
    end
  end

  def rsvp_index
    @rsvps = Rsvp.all
    @rsvp_count = Rsvp.all.size
    @yes = Rsvp.where("attending like ?", "%Yes%").size
    @nos = Rsvp.where("attending like ?", "%No%").size
  end

  def video

  end

  private

  def rsvp_params
    params.require(:rsvp).permit(:name, :surname, :email, :attending, :guests_number, :companions, :dietary_restrictions, :other_dietary_restrictions, :songs)
  end

  def afterparty_params
    params.require(:afterparty).permit(:name, :number, :days, :comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <!-- Bootstrap CSS for styling and layout -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.css" integrity="sha256-a2tobsqlbgLsWs7ZVUGgP5IvWZsx8bTNQpzsqCSm5mk=" crossorigin="anonymous" />
    <!-- Tittle and favicon -->
    <title>Christina & Alex</title>
    <link rel="shortcut icon" href="images/logo.png">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="photo-section" >
      <div id="filter" class="jumbotron">
      <div id="navbar" class="container">
        <section class="animated fadeInDown" time="3s">
        <div class="row" id="large-view">
          <div class="col-2">
            <%= link_to t('.rsvp'), rsvp_path, class: 'section' %>
          </div>
          <div class="col-2">
            <%= link_to t('.accommodation'), accommodation_path, class: 'section' %>
          </div>
          <div class="col-4">
            <h4><%= link_to 'Christina & Alex', root_path, class: 'names' %></h4>
          </div>
          <div class="col-2">
            <%= link_to t('.afterparty'), afterparty_path, class: 'section' %>
          </div>
          <div class="col-2">
            <%= link_to 'VIDEO', video_path, class: 'section' %>
          </div>
        </div>
        <div class="row" id="small-view">
          <div class="col-2">
            <%= link_to 'RSVP', rsvp_path, class: 'section' %>
          </div>
          <div class="col-2">
            <%= link_to t('.stay'), accommodation_path, class: 'section' %>
          </div>
          <div class="col-4">
            <h4><%= link_to 'Christina & Alex', root_path, class: 'names' %></h4>
          </div>
          <div class="col-2">
            <%= link_to t('.trip'), afterparty_path, class: 'section' %>
          </div>
          <div class="col-2">
            <%= link_to 'VIDEO', video_path, class: 'section' %>
          </div>
        </div>
      </section>
      </div>
      <div id="greeting" class="greeting">
        <section class="animated fadeInUp" time="3s">
        <h1><%= t('.greeting') %></h1>
      </section>
      </div>
      <br>
        <section class="animated fadeInUp" time="3s">
          <div id="date" class="date">
            <p><%= t('.date') %></p>
          </div>
        </section>
        <section class="animated fadeInUp" time="3s">
          <div id="date" class="date">
            <%= t('.language') %> &nbsp
            <%= link_to_unless_current "English", locale: "en" %>
             &nbsp | &nbsp
            <%= link_to_unless_current "Español", locale: "es" %>
          </div>
        </section>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/accommodation.html.erb
<!DOCTYPE html>
<html class="accommodation" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>accommodation</title>
  </head>
  <body>
    <div class="content" id="row1">
      <div class="center">
        <br>
        <img src="../images/pick_up.png" class="circle">
        <br>
        <br>
        <h1><%= t('.transportion') %></h1>
        <p>
          Ajuntament de València
          <br>
          Plaça de l'Ajuntament, 1
          <br>
          46002 València
          <br>
          <a href="https://goo.gl/maps/5RKnkU4GDvf9iYY37" target="_blank"><%= t('.map') %></a>
          <br>
          <br>
          <%= t('.transportation_content') %>
        </p>
      </div>
    </div>
    <div class="content" id="row2">
      <div class="center">
        <br>
        <br>
        <img src="../images/hotels.png" class="circle">
        <br>
        <br>
        <h1><%= t('.accommodation') %></h1>
        <%= t('.accommodation_content') %>
        <br>
        <br>
        <div class="row">
          <div class="col-4">
            <a class="hotel" href='https://www.hostalam.com/' target="_blank">Hostal Antigua Morellana</a>
          </div>
          <div class="col-4">
            <a class="hotel" href='https://www.melia.com/es/hoteles/espana/valencia/melia-plaza/index.htm' target="_blank">Hotal Melia Plaza</a>
          </div>
          <div class="col-4">
            <a class="hotel" href='https://casualhoteles.com/hoteles-valencia/casual-valencia-vintage' target="_blank">Hotel Casual Vintage</a>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-4">
            <a class="hotel" href='https://creativeroomsvlc.com/' target="_blank">Boutique Creative Rooms</a>
          </div>
          <div class="col-4">
          <a class="hotel" href='https://www.hotelvenecia.com/'target="_blank">Hostal Venecia</a>
          </div>
          <div class="col-4">
          <a class="hotel" href='http://www.hostalmoratin.es/' target="_blank">Hostal Moratin</a>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/accommodations.html.erb
<!DOCTYPE html>
<html class="accommodations" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>accommodations</title>
  </head>
  <body>
    <div class="content" id="row1">
      <div class="center">
        <br>
        <img src="images/pick_up.png" class="circle">
        <br>
        <br>
        <h1>The Pick Up</h1>
        <p>
          Ajuntament de València
          <br>
          Plaça de l'Ajuntament, 1
          <br>
          46002 València
          <br>
          <a href="https://goo.gl/maps/5RKnkU4GDvf9iYY37">View Map</a>
          <br>
          <br>
          For your convenience, we have arranged transportion to and from the venue. The shuttle will collect guests at the city center pick-up location and depart at 8:15PM. Shuttle service back to city center will start at 1:00AM in intervals of 60 minutes (1:00, 2:00, 3:00, etc.). The final shuttle will be determined by how long we keep the party going!
        </p>
      </div>
    </div>
    <div class="content" id="row2">
      <div class="center">
        <br>
        <br>
        <img src="images/hotels.png" class="circle">
        <br>
        <br>
        <h1>The Accommodations</h1>
        For our out of town guests, here are some recommendations for accomodations that are both centrally located and close to the shuttle pick-up location. The city hall plaza is also well-connected to public transportation if you are interested in exploring Valencia. Alternatively there are plenty of other hotels and AirBnBs in the local area. Please do let us know if you need any assistance with booking.
        <br>
        <br>
        <div class="row">
          <div class="col-4">
            <a class="hotel" href='https://www.hostalam.com/'>Hostal Antigua Morellana</a>
          </div>
          <div class="col-4">
            <a class="hotel" href='https://www.melia.com/es/hoteles/espana/valencia/melia-plaza/index.htm'>Hotal Melia Plaza</a>
          </div>
          <div class="col-4">
            <a class="hotel" href='https://casualhoteles.com/hoteles-valencia/casual-valencia-vintage'>Hotel Casual Vintage</a>
          </div>
        </div>
        <br>
        <div class="row">
          <div class="col-4">
            <a class="hotel" href='https://creativeroomsvlc.com/'>Boutique Creative Rooms</a>
          </div>
          <div class="col-4">
          <a class="hotel" href='https://www.hotelvenecia.com/'>Hostal Venecia</a>
          </div>
          <div class="col-4">
          <a class="hotel" href='http://www.hostalmoratin.es/'>Hostal Moratin</a>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/pages/afterparty.html.erb
<!DOCTYPE html>
<html class="afterparty" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>afterparty</title>
  </head>
  <body>
    <div class="content" id="row1">
      <div class="center">
        <img src="../images/ibiza.png" class="circle">
        <br>
        <br>
        <h1><%= t('.trip') %></h1>
        <p>
          Ibiza
          <br>
          <%= t('.islands') %>
          <br>
          <a href="https://goo.gl/maps/USAqXQVrXQvpDCb48" target="_blank"><%= t('.map') %></a>
          <br>
          <br>
          <%= t('.trip_content') %>
      </div>
    </div>
    <div class="content" id="row2">
      <br>
      <br>
      <br>
      <br>
      <div class="box" onsubmit="confirmSubmission()">
        <h2><%= t('.joining') %></h2>
          <%= form_for :afterparty, url: afterparty_path do |f| %>
          <div class="inputBox">
            <%= f.text_field :name, :required => true%>
            <label><%= t('.name') %></label>
          </div>
          <div class="inputBox">
            <%= f.text_field :number, :required => true%>
            <label><%= t('.number') %></label>
          </div>
          <div class="inputBox">
            <%= f.text_field :days, :required => true%><br>
            <label><%= t('.days') %></label>
          </div>
          <div class="inputBox">
          <select-label><%= t('.comment') %></select-label>
            <%= f.text_area :comment, :required => false%><br><br>
          </div>
          <br>
          <%= f.submit t('.submit') %>
          <div class="inputBox">
          <br>
          <select-label><%= t('.thanks') %></select-label>
          <br>
          <select-label><%= t('.message') %></select-label>
          </div>
          <% end %>
      </div>
      <script>
        function confirmSubmission() {
          alert("The form was submitted");
        }
      </script>
    </div>
  </body>
</html>

app/views/pages/afterparty_index.html.erb
<!DOCTYPE html>
<html class="index" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>afterparty_index</title>
  </head>
  <body>
    <br>
    <br>
    <br>
    <br>
    <div class="box">
      <h5>
  		    <%= @afterparty_count %> Responses:
      </h5>
    </div>
    <% @afterparties.each do |afterparty| %>
      <div class="box">
        <h5>
          <p>Guest name: <%= afterparty.name %></p>
          <p class="phone">Guest phone number: <%= afterparty.number %></p>
          <p class="days"><%= afterparty.name %> is staying <%= afterparty.days %> days</p>
          <p class="comment"><%= afterparty.name %> says <%= afterparty.comment %></p>
        </h5>
      </div>
    <% end %>
  </body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html class="home" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>home</title>
  </head>
  <body>
    <div class="content" id="row1">
      <div class="center">
        <img src="images/venue1.png" class="circle">
        <br>
        <br>
        <h1><%= t('.venue') %></h1>
        <p>
          Masía Xamandreu
          <br>
          Carretera Godella - Bétera CV310, Km 4
          <br>
          46110 Godella, Valencia
          <br>
          <a href="https://goo.gl/maps/KgXPebFEz9QeU4kJ8" target="_blank"><%= t('.map') %></a>
        </p>
      </div>
    </div>
    <div class="content" id="row2">
      <div class="center">
        <img src="images/venue2.png" class="circle">
        <br>
        <br>
        <h1><%= t('.schedule') %></h1>
        <p>
          <%= t('.cocktails') %>
          <br>
          <%= t('.dinner') %>
          <br>
          <%= t('.fiesta') %>
          <br>
          <br>
          <%= t('.schedule_content') %>
          <br>
        </p>
      </div>
    </div>
  </body>
</html>

app/views/pages/rsvp.html.erb
<!DOCTYPE html>
<html class="rsvp" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>rsvp</title>
  </head>
  <body>
    <br>
    <br>
    <div class="box" onsubmit="confirmSubmission()">
      <h2>RSVP</h2>
        <%= form_for :rsvp, url: rsvp_path do |f| %>
        <div class="inputBox">
          <%= f.text_field :name, :required => true%>
          <label><%= t('.name') %></label>
        </div>
        <div class="inputBox">
          <%= f.text_field :email, :required => true%><br>
          <label>Email</label>
        </div>
        <div class="inputBox">
          <select-label><%= t('.attending') %></select-label>
          <%= f.select :attending, [t('.yes'),'No'], :required => true%><br><br>
        </div>
        <div class="inputBox">
          <%= f.text_field :guests_number, :required => true%><br>
          <label><%= t('.guests_number') %></label>
        </div>
        <div class="inputBox">
        <select-label><%= t('.companions') %></select-label>
          <%= f.text_area :companions, :required => true%><br><br>
        </div>
        <div class="inputBox">
          <%= f.text_field :dietary_restrictions, :required => true%><br>
          <label><%= t('.dietary_restrictions') %></label>
        </div>
        <div class="inputBox">
        <select-label><%= t('.songs') %></select-label>
          <%= f.text_area :songs, :required => false%><br>
        </div>
        <br>
        <%= f.submit t('.submit') %>
        <% end %>
    </div>
    <script>
      function confirmSubmission() {
        alert("The form was submitted");
      }
    </script>
  </body>
</html>

app/views/pages/rsvp_index.html.erb
<!DOCTYPE html>
<html class="index" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>rsvp_index</title>
  </head>
  <body>
    <br>
    <br>
    <br>
    <br>
    <div class="box">
      <h5>
  		    <%= @rsvp_count %> Responses: <%= @yes %> Yes and <%= @nos %> No
      </h5>
    </div>
    <% @rsvps.each do |rsvp| %>
      <div class="box">
        <h5>
  			   <p class="name">Guest name: <%= rsvp.name %></p>
  			   <p class="email">Guest email: <%= rsvp.email %></p>
  			   <p class="attending"><%= rsvp.name %> is <%= rsvp.attending %> attending</p>
  			   <p class="guests_number"><%= rsvp.name %> is coming with <%= rsvp.guests_number %></p>
  			   <p class="companions"><%= rsvp.companions %></p>
  			   <p class="dietary_restrictions">Dietary restrictions: <%= rsvp.dietary_restrictions %></p>
  			   <p class="songs">Songs: <%= rsvp.songs %></p>
        </h5>
			</div>
		<% end %>
  </body>
</html>

app/views/pages/video.html.erb
<!DOCTYPE html>
<html class="video" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>video</title>
  </head>
  <body>
    <br>
    <br>
    <div class="box">
      <%= video_tag "/videos/Invite.mp4", :size => "360x640", :controls => true %>
    </div>
  </body>
</html>